<?php

use Illuminate\Database\Seeder;

class VastechSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('tenants')->insert([
            'name'                              => 'tenant',
            'email'                             => 'tenant@tenant.com',
            'password'                          => bcrypt('tenant123'),
        ]);

        DB::table('companies')->insert([
            'tenant_id'                         => '1',
            'name'                              => 'Joni',
        ]);

        DB::table('users')->insert([
            'tenant_id'                         => '1',
            'company_id'                        => '1',
            'name'                              => 'user',
            'email'                             => 'user@user.com',
            'password'                          => bcrypt('user123'),
        ]);

        DB::table('company_settings')->insert([
            'tenant_id'                         => '1',
            'company_id'                        => '1',
            'user_id'                           => '1',
            'name'                              => 'company',
        ]);

        DB::table('company_logos')->insert([
            'tenant_id'                         => '1',
            'company_id'                        => '1',
            'user_id'                           => '1',
            'mime'                              => 'image/jpeg',
            'original_filename'                 => 'defaultlogo.jpg',
            'filename'                          => 'defaultlogo.jpg',
        ]);

        DB::table('coa_categories')->insert([
            [
                'name'                              => 'Account Receivable (A/R)',
            ],
            [
                'name'                              => 'Other Current Assets',
            ],
            [
                'name'                              => 'Cash & Bank',
            ],
            [
                'name'                              => 'Inventory',
            ],
            [
                'name'                              => 'Fixed Assets',
            ],
            [
                'name'                              => 'Other Assets',
            ],
            [
                'name'                              => 'Depreciation & Amortization',
            ],
            [
                'name'                              => 'Accounts Payable (A/P)',
            ],
            [
                'name'                              => 'Credit Card',
            ],
            [
                'name'                              => 'Other Current Liabilities',
            ],
            [
                'name'                              => 'Long Term Liabilities',
            ],
            [
                'name'                              => 'Equity',
            ],
            [
                'name'                              => 'Income',
            ],
            [
                'name'                              => 'Other Income',
            ],
            [
                'name'                              => 'Cost of Sales',
            ],
            [
                'name'                              => 'Expenses',
            ],
            [
                'name'                              => 'Other Expense',
            ],
        ]);

        DB::table('other_payment_methods')->insert([
            [
                'name'                              => 'Cash',
            ],
            [
                'name'                              => 'Check',
            ],
            [
                'name'                              => 'Bank Transfer',
            ],
            [
                'name'                              => 'Credit Card',
            ],
        ]);

        DB::table('other_product_categories')->insert([
            'tenant_id'                         => '1',
            'company_id'                        => '1',
            'user_id'                           => '1',
            'name'                              => 'Unsigned Category',
        ]);

        DB::table('other_statuses')->insert([
            [
                'name'                              => 'Open',
            ],
            [
                'name'                              => 'Closed',
            ],
            [
                'name'                              => 'Paid',
            ],
            [
                'name'                              => 'Partial',
            ],
            [
                'name'                              => 'Overdue',
            ],
            [
                'name'                              => 'Sent',
            ],
            [
                'name'                              => 'Active',
            ],
            [
                'name'                              => 'Sold',
            ],
            [
                'name'                              => 'Disposed',
            ],
        ]);

        DB::table('coas')->insert([
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '1-10001',
                'name'                              => 'Cash',
                'coa_category_id'                   => '3',
                //'cashbank'                          => '1',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '1-10002',
                'name'                              => 'Bank Account',
                'coa_category_id'                   => '3',
                //'cashbank'                          => '1',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '1-10003',
                'name'                              => 'Giro',
                'coa_category_id'                   => '3',
                //'cashbank'                          => '1',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '1-10100',
                'name'                              => 'Account Receivable',
                'coa_category_id'                   => '1',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '1-10101',
                'name'                              => 'Unbilled Account Receivable',
                'coa_category_id'                   => '1',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '1-10102',
                'name'                              => 'Doubtful Receivable',
                'coa_category_id'                   => '1',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '1-10200',
                'name'                              => 'Inventory',
                'coa_category_id'                   => '4',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '1-10300',
                'name'                              => 'Other Receivables',
                'coa_category_id'                   => '2',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '1-10301',
                'name'                              => 'Employee Receivables',
                'coa_category_id'                   => '2',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '1-10400',
                'name'                              => 'Undeposited Funds',
                'coa_category_id'                   => '2',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '1-10401',
                'name'                              => 'Other Current Assets',
                'coa_category_id'                   => '2',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '1-10402',
                'name'                              => 'Prepaid Expenses',
                'coa_category_id'                   => '2',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '1-10403',
                'name'                              => 'Advances',
                'coa_category_id'                   => '2',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '1-10500',
                'name'                              => 'VAT In',
                'coa_category_id'                   => '2',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '1-10501',
                'name'                              => 'Prepaid Income Tax - PPh 22',
                'coa_category_id'                   => '2',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '1-10502',
                'name'                              => 'Prepaid Income Tax - PPh 23',
                'coa_category_id'                   => '2',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '1-10503',
                'name'                              => 'Prepaid Income Tax - PPh 25',
                'coa_category_id'                   => '2',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '1-10700',
                'name'                              => 'Fixed Assets - Land',
                'coa_category_id'                   => '5',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '1-10701',
                'name'                              => 'Fixed Assets - Building',
                'coa_category_id'                   => '5',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '1-10702',
                'name'                              => 'Fixed Assets - Building Improvements',
                'coa_category_id'                   => '5',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '1-10703',
                'name'                              => 'Fixed Assets - Vehicles',
                'coa_category_id'                   => '5',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '1-10704',
                'name'                              => 'Fixed Assets - Machinery & Equipment',
                'coa_category_id'                   => '5',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '1-10705',
                'name'                              => 'Fixed Assets - Office Equipment',
                'coa_category_id'                   => '5',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '1-10706',
                'name'                              => 'Fixed Assets - Leased Asset',
                'coa_category_id'                   => '5',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '1-10707',
                'name'                              => 'Intangible Assets',
                'coa_category_id'                   => '5',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '1-10708',
                'name'                              => 'Trade Mark',
                'coa_category_id'                   => '5',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '1-10709',
                'name'                              => 'Copyright',
                'coa_category_id'                   => '5',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '1-10710',
                'name'                              => 'Good Will',
                'coa_category_id'                   => '5',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '1-10751',
                'name'                              => 'Accumulated Depreciation - Building',
                'coa_category_id'                   => '7',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '1-10752',
                'name'                              => 'Accumulated Depreciation - Building Improvements',
                'coa_category_id'                   => '7',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '1-10753',
                'name'                              => 'Accumulated Depreciation - Vehicles',
                'coa_category_id'                   => '7',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '1-10754',
                'name'                              => 'Accumulated Depreciation - Machinery & Equipment',
                'coa_category_id'                   => '7',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '1-10755',
                'name'                              => 'Accumulated Depreciation - Office Equipment',
                'coa_category_id'                   => '7',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '1-10756',
                'name'                              => 'Accumulated Depreciation - Leased Asset',
                'coa_category_id'                   => '7',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '1-10757',
                'name'                              => 'Accumulated Amortization',
                'coa_category_id'                   => '7',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '1-10758',
                'name'                              => 'Accumulated Amortization : Trade Mark',
                'coa_category_id'                   => '7',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '1-10759',
                'name'                              => 'Accumulated Amortization : Copyright',
                'coa_category_id'                   => '7',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '1-10760',
                'name'                              => 'Accumulated Amortization : Good Will',
                'coa_category_id'                   => '7',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '1-10800',
                'name'                              => 'Investments',
                'coa_category_id'                   => '6',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '2-20100',
                'name'                              => 'Trade Payable',
                'coa_category_id'                   => '8',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '2-20101',
                'name'                              => 'Unbilled Accounts Payable',
                'coa_category_id'                   => '8',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '2-20200',
                'name'                              => 'Other Payables',
                'coa_category_id'                   => '10',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '2-20201',
                'name'                              => 'Salaries Payable',
                'coa_category_id'                   => '10',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '2-20202',
                'name'                              => 'Dividends Payable',
                'coa_category_id'                   => '10',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '2-20203',
                'name'                              => 'Unearned Revenue',
                'coa_category_id'                   => '10',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '2-20301',
                'name'                              => 'Accrued Utilities',
                'coa_category_id'                   => '10',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '2-20302',
                'name'                              => 'Accrued Interest',
                'coa_category_id'                   => '10',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '2-20399',
                'name'                              => 'Other Accrued Expenses',
                'coa_category_id'                   => '10',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '2-20400',
                'name'                              => 'Bank Loans',
                'coa_category_id'                   => '10',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '2-20500',
                'name'                              => 'VAT Out',
                'coa_category_id'                   => '10',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '2-20501',
                'name'                              => 'Tax Payable - PPh 21',
                'coa_category_id'                   => '10',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '2-20502',
                'name'                              => 'Tax Payable - PPh 22',
                'coa_category_id'                   => '10',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '2-20503',
                'name'                              => 'Tax Payable - PPh 23',
                'coa_category_id'                   => '10',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '2-20504',
                'name'                              => 'Tax Payable - PPh 29',
                'coa_category_id'                   => '10',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '2-20599',
                'name'                              => 'Other Taxes Payable',
                'coa_category_id'                   => '10',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '2-20600',
                'name'                              => 'Loan from Shareholders',
                'coa_category_id'                   => '10',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '2-20601',
                'name'                              => 'Other Current Liabilities',
                'coa_category_id'                   => '10',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '2-20700',
                'name'                              => 'Employee Benefit Liabilities',
                'coa_category_id'                   => '11',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '3-30000',
                'name'                              => 'Paid In Capital',
                'coa_category_id'                   => '12',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '3-30001',
                'name'                              => 'Additional Paid In Capital',
                'coa_category_id'                   => '12',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '3-30100',
                'name'                              => 'Retained Earnings',
                'coa_category_id'                   => '12',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '3-30200',
                'name'                              => 'Dividends',
                'coa_category_id'                   => '12',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '3-30300',
                'name'                              => 'Other Comprehensive Income',
                'coa_category_id'                   => '12',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '3-30999',
                'name'                              => 'Opening Balance Equity',
                'coa_category_id'                   => '12',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '4-40000',
                'name'                              => 'Revenue',
                'coa_category_id'                   => '13',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '4-40100',
                'name'                              => 'Sales Discount',
                'coa_category_id'                   => '13',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '4-40200',
                'name'                              => 'Sales Return',
                'coa_category_id'                   => '13',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '4-40201',
                'name'                              => 'Unbilled Revenues',
                'coa_category_id'                   => '13',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '5-50000',
                'name'                              => 'Cost of Sales',
                'coa_category_id'                   => '15',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '5-50100',
                'name'                              => 'Purchase Discounts',
                'coa_category_id'                   => '15',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '5-50200',
                'name'                              => 'Purchase Return',
                'coa_category_id'                   => '15',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '5-50300',
                'name'                              => 'Shipping/Freight & Delivery',
                'coa_category_id'                   => '15',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '5-50400',
                'name'                              => 'Import Charges',
                'coa_category_id'                   => '15',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '5-50500',
                'name'                              => 'Cost of Production',
                'coa_category_id'                   => '15',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60000',
                'name'                              => 'Selling Expenses',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60001',
                'name'                              => 'Advertising & Promotion',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60002',
                'name'                              => 'Commission & Fees',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60003',
                'name'                              => 'Fuel, Toll and Parking - Sales',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60004',
                'name'                              => 'Travelling - Sales',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60005',
                'name'                              => 'Communication - Sales',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60006',
                'name'                              => 'Other Marketting',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60100',
                'name'                              => 'General & Administrative Expenses',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60101',
                'name'                              => 'Salaries',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60102',
                'name'                              => 'Wages',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60103',
                'name'                              => 'Meals and Transport',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60104',
                'name'                              => 'Overtime',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60105',
                'name'                              => 'Medical',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60106',
                'name'                              => 'THR and Bonus',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60107',
                'name'                              => 'Jamsostek',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60108',
                'name'                              => 'Incentive',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60109',
                'name'                              => 'Severance',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60110',
                'name'                              => 'Other Benefit and Allowances',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60200',
                'name'                              => 'Donations',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60201',
                'name'                              => 'Entertainment',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60202',
                'name'                              => 'Fuel, Toll and Parking - General',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60203',
                'name'                              => 'Repair and Maintenance',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60204',
                'name'                              => 'Travelling - General',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60205',
                'name'                              => 'Meals',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60206',
                'name'                              => 'Communication - General',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60207',
                'name'                              => 'Dues & Subscription',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60208',
                'name'                              => 'Insurance',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60209',
                'name'                              => 'Legal & Professional Fees',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60210',
                'name'                              => 'Employee Benefit Expense',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60211',
                'name'                              => 'Utilities Expense',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60212',
                'name'                              => 'Training & Developments',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60213',
                'name'                              => 'Bad Debt Expense',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60214',
                'name'                              => 'Taxes and Licenses',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60215',
                'name'                              => 'Penalties',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60216',
                'name'                              => 'Electricity',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60217',
                'name'                              => 'Water',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60218',
                'name'                              => 'Service Charge',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60219',
                'name'                              => 'Subscribe Software',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60300',
                'name'                              => 'Office Expense',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60301',
                'name'                              => 'Stationery & Printing',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60302',
                'name'                              => 'Stamp & Duty',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60303',
                'name'                              => 'Securities and Cleaning',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60304',
                'name'                              => 'Supplies and Materials',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60305',
                'name'                              => 'Subcontractors',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60400',
                'name'                              => 'Rental Expense - Building',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60401',
                'name'                              => 'Rental Expense - Vehicle',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60402',
                'name'                              => 'Rental Expense - Lease',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60403',
                'name'                              => 'Rental Expense - Others',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60500',
                'name'                              => 'Depreciation - Building',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60501',
                'name'                              => 'Depreciation - Building Improvements',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60502',
                'name'                              => 'Depreciation - Vehicle',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60503',
                'name'                              => 'Depreciation - Machinery & Equipment',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60504',
                'name'                              => 'Depreciation - Office Equipment',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60599',
                'name'                              => 'Depreciation - Leased Asset',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60600',
                'name'                              => 'Amortization: Trade Mark',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60601',
                'name'                              => 'Amortization: Copyright',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60602',
                'name'                              => 'Amortization: Good Will',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '6-60216',
                'name'                              => 'Waste Goods Expense',
                'coa_category_id'                   => '16',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '7-70000',
                'name'                              => 'Interest Income - Bank',
                'coa_category_id'                   => '14',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '7-70001',
                'name'                              => 'Interest Income - Time Deposit',
                'coa_category_id'                   => '14',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '7-70002',
                'name'                              => 'Rounding',
                'coa_category_id'                   => '14',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '7-70099',
                'name'                              => 'Other Income',
                'coa_category_id'                   => '14',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '8-80000',
                'name'                              => 'Interest Expense',
                'coa_category_id'                   => '17',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '8-80001',
                'name'                              => 'Provision',
                'coa_category_id'                   => '17',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '8-80002',
                'name'                              => '(Gain)/Loss on Disposal of Fixed Assets',
                'coa_category_id'                   => '17',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '8-80100',
                'name'                              => 'Inventory Adjustments',
                'coa_category_id'                   => '17',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '8-80999',
                'name'                              => 'Other Miscellaneous Expense',
                'coa_category_id'                   => '17',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '9-90000',
                'name'                              => 'Income Taxes - Current',
                'coa_category_id'                   => '17',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'code'                              => '9-90001',
                'name'                              => 'Income Taxes - Deferred',
                'coa_category_id'                   => '17',
            ],
        ]);

        DB::table('other_taxes')->insert([
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'name'                              => 'None',
                'rate'                              => '0',
                'sell_tax_account'                  => '50',
                'buy_tax_account'                   => '14',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'name'                              => 'PPN',
                'rate'                              => '10',
                'sell_tax_account'                  => '50',
                'buy_tax_account'                   => '14',
            ],
        ]);

        DB::table('other_units')->insert([
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'name'                              => 'PCS',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'name'                              => 'BTG',
            ],
        ]);

        DB::table('other_terms')->insert([
            [
                'name'                              => 'Custom',
                'length'                            => '0',
            ],
            [
                'name'                              => 'Net 30',
                'length'                            => '30',
            ],
            [
                'name'                              => 'Cash on Delivery',
                'length'                            => '0',
            ],
            [
                'name'                              => 'Net 15',
                'length'                            => '15',
            ],
            [
                'name'                              => 'Net 60',
                'length'                            => '60',
            ],
        ]);

        DB::table('default_accounts')->insert([
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'name'                              => 'default_sales_revenue',
                'account_id'                        => '65',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'name'                              => 'default_sales_discount',
                'account_id'                        => '66',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'name'                              => 'default_sales_return',
                'account_id'                        => '67',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'name'                              => 'default_sales_shipping',
                'account_id'                        => '136',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'name'                              => 'default_unearned_revenue',
                'account_id'                        => '45',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'name'                              => 'default_unbilled_sales',
                'account_id'                        => '68',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'name'                              => 'default_unbilled_receivable',
                'account_id'                        => '5',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'name'                              => 'default_sales_tax_receiveable',
                'account_id'                        => '50',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'name'                              => 'default_purchase',
                'account_id'                        => '69',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'name'                              => 'default_purchase_shipping',
                'account_id'                        => '72',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'name'                              => 'default_prepayment',
                'account_id'                        => '12',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'name'                              => 'default_unbilled_payable',
                'account_id'                        => '41',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'name'                              => 'default_purchase_tax_receivable',
                'account_id'                        => '14',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'name'                              => 'default_account_receivable',
                'account_id'                        => '4',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'name'                              => 'default_account_payable',
                'account_id'                        => '40',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'name'                              => 'default_inventory',
                'account_id'                        => '7',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'name'                              => 'default_inventory_general',
                'account_id'                        => '140',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'name'                              => 'default_inventory_waste',
                'account_id'                        => '132',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'name'                              => 'default_inventory_production',
                'account_id'                        => '74',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'name'                              => 'default_opening_balance_equity',
                'account_id'                        => '64',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'name'                              => 'default_fixed_asset',
                'account_id'                        => '23',
            ],
        ]);

        DB::table('contacts')->insert([
            'tenant_id'                         => '1',
            'company_id'                        => '1',
            'user_id'                           => '1',
            'display_name'                      => 'contact all type',
            'account_receivable_id'             => '4',
            'account_payable_id'                => '40',
            'term_id'                           => '1',
        ]);

        DB::table('products')->insert([
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'name'                              => 'contoh product pcs',
                'other_product_category_id'         => '1',
                'other_unit_id'                     => '1',
                'qty'                               => '0',
            ],
            [
                'tenant_id'                         => '1',
                'company_id'                        => '1',
                'user_id'                           => '1',
                'name'                              => 'contoh product btg',
                'other_product_category_id'         => '1',
                'other_unit_id'                     => '2',
                'qty'                               => '0',
            ],
        ]);

        DB::table('roles')->insert([
            [
                'name'                              => 'Owner',
                'guard_name'                        => 'web',
            ],
            [
                'name'                              => 'Ultimate',
                'guard_name'                        => 'web',
            ],
            [
                'name'                              => 'Asset',
                'guard_name'                        => 'web',
            ],
            [
                'name'                              => 'Sales Quote',
                'guard_name'                        => 'web',
            ],
            [
                'name'                              => 'Sales Order',
                'guard_name'                        => 'web',
            ],
            [
                'name'                              => 'Sales Delivery',
                'guard_name'                        => 'web',
            ],
            [
                'name'                              => 'Sales Invoice',
                'guard_name'                        => 'web',
            ],
            [
                'name'                              => 'Sales Payment',
                'guard_name'                        => 'web',
            ],
            [
                'name'                              => 'Sales Return',
                'guard_name'                        => 'web',
            ],
            [
                'name'                              => 'Purchase Quote',
                'guard_name'                        => 'web',
            ],
            [
                'name'                              => 'Purchase Order',
                'guard_name'                        => 'web',
            ],
            [
                'name'                              => 'Purchase Delivery',
                'guard_name'                        => 'web',
            ],
            [
                'name'                              => 'Purchase Invoice',
                'guard_name'                        => 'web',
            ],
            [
                'name'                              => 'Purchase Payment',
                'guard_name'                        => 'web',
            ],
            [
                'name'                              => 'Purchase Return',
                'guard_name'                        => 'web',
            ],
            [
                'name'                              => 'Expense',
                'guard_name'                        => 'web',
            ],
            [
                'name'                              => 'Production',
                'guard_name'                        => 'web',
            ],
            [
                'name'                              => 'Contact',
                'guard_name'                        => 'web',
            ],
            [
                'name'                              => 'Good & Services',
                'guard_name'                        => 'web',
            ],
            [
                'name'                              => 'Stock Adjustment',
                'guard_name'                        => 'web',
            ],
            [
                'name'                              => 'Warehouses',
                'guard_name'                        => 'web',
            ],
            [
                'name'                              => 'Warehouse Transfer',
                'guard_name'                        => 'web',
            ],
            [
                'name'                              => 'Cash & Bank',
                'guard_name'                        => 'web',
            ],
            [
                'name'                              => 'Chart of Account',
                'guard_name'                        => 'web',
            ],
            [
                'name'                              => 'Other List',
                'guard_name'                        => 'web',
            ],
        ]);

        DB::table('permissions')->insert([
            [
                'name'                              => 'Create',
                'guard_name'                        => 'web',
            ],
            [
                'name'                              => 'Edit',
                'guard_name'                        => 'web',
            ],
            [
                'name'                              => 'Delete',
                'guard_name'                        => 'web',
            ],
        ]);

        DB::table('model_has_roles')->insert([
            [
                'role_id'                         => '1',
                'model_type'                      => 'App\User',
                'model_id'                        => '1',
            ],
        ]);

        DB::table('model_has_permissions')->insert([
            [
                'permission_id'                   => '1',
                'model_type'                      => 'App\User',
                'model_id'                        => '1',
            ],
            [
                'permission_id'                   => '2',
                'model_type'                      => 'App\User',
                'model_id'                        => '1',
            ],
            [
                'permission_id'                   => '3',
                'model_type'                      => 'App\User',
                'model_id'                        => '1',
            ],
        ]);
    }
}
